export enum CardEffect {
  None = 0,
  AntManBuff = 1,
  AngelaBuff = 2,
  ArmorPreventDestroy = 3,
  ColossusImmune = 4,
  MisterFantasticBuff = 5,
  CosmoBlockOnReveal = 6,
  NamorBuff = 7,
  IronManDoublePower = 8,
  KlawRightBuff = 9,
  SpectrumBuffOngoing = 10,
  OnslaughtDoubleOngoing = 11,
  HawkeyeNextTurnBuff = 12,
  MedusaCenterBuff = 13,
  StarLordOpponentPlayedBuff = 14,
  PunisherEnemyBuff = 15,
  SentinelAddToHand = 16,
  WolfsbaneBuff = 17,
  NightcrawlerMove = 18,
}
