export enum ImageEnum {
  Background = 'Background',
  Example = 'Example',
  CardAntMan = 'CardAntMan',
  CardAngela = 'CardAngela',
  CardArmor = 'CardArmor',
  CardColossus = 'CardColossus',
  CardCosmo = 'CardCosmos',
  CardIronMan = 'CardIronMan',
  CardMrFantastic = 'CardMrFantastic',
  CardNamor = 'CardNamor',
  CardNightcrawler = 'CardNightcrawler',
  CardKlaw = 'CardKlaw',
  CardSpectrum = 'CardSpectrum',
  CardOnslaught = 'CardOnslaught',
  CardAbomination = 'CardAbomination',
  CardCyclops = 'CardCyclops',
  CardHawkEye = 'CardHawkEye',
  CardHulk = 'CardHulk',
  CardMedusa = 'CardMedusa',
  CardMistyKnight = 'CardMistyKnight',
  CardPunisher = 'CardPunisher',
  CardQuickSilver = 'CardQuickSilver',
  CardSentinel = 'CardSentinel',
  CardWolfsbane = 'CardWolfsbane',
  CardStarlord = 'CardStarlord',
  CardTheThing = 'CardTheThing',
}
